baseURL = "https://nubestack.com/"
languageCode = "en-us"
#title = "Arcana for Hugo"
theme = "hugo-arcana"
copyright = "Â© NubeStack. All rights reserved"

# Menu Configuration - Easy to manage menu order and items
[menu]
[[menu.main]]
name = "Private Cloud Solutions"
url = "/services/private-cloud"
parent = "Services"
weight = 15

[[menu.main]]
name = "Container Orchestration"
url = "/services/container-orchestration"
parent = "Services"
weight = 16

[[menu.main]]
name = "NFV Solutions"
url = "/services/nfv"
parent = "Services"
weight = 17

[[menu.main]]
name = "Managed Services"
url = "/services/managed-services"
parent = "Services"
weight = 18

[[menu.main]]
name = "Public Cloud Solutions"
url = "/services/public-cloud"
parent = "Services"
weight = 19

[[menu.main]]
name = "Infrastructure Automation"
url = "/services/automation"
parent = "Services"
weight = 20
[[menu.main]]
name = "Services"
url = "#"
weight = 1


[[menu.main]]
name = "Industry"
url = "/industry"
weight = 2

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 3

[[menu.main]]
name = "About us"
url = "/about"
weight = 4

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 5

[taxonomies]
    tag = "tags"

[params]
    description = "A business/corporate style responsive site template."
    images = ['images/metaimage.jpg']
    show_post_dates = false

   [[params.social]]
        title = "WhatsApp"
        icon = "fa-whatsapp"
        url = "https://www.linkedin.com/company/nubestack"
    [[params.social]]
        title = "LinkedIn"
        icon = "fa-linkedin-in"
        url = "https://www.linkedin.com/company/nubestack"


    [params.footer]

        [[params.footer.links]]
            header = "Links to Stuff"
        [[params.footer.links.links]]
            title = "Mattis et quis rutrum"
            url = "#"
        [[params.footer.links.links]]
            title = "Suspendisse amet varius"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum accumsan dolor"
            url = "#"

        [[params.footer.links]]
            header = "More Links to Stuff"
        [[params.footer.links.links]]
            title = "Duis neque nisi dapibus"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum accumsan sed"
            url = "#"
        [[params.footer.links.links]]
            title = "Mattis et sed accumsan"
            url = "#"

        [[params.footer.links]]
            header = "Additional Resources"
        [[params.footer.links.links]]
            title = "Cloud Migration Guide"
            url = "#"
        [[params.footer.links.links]]
            title = "DevOps Best Practices"
            url = "#"
        [[params.footer.links.links]]
            title = "Security Compliance"
            url = "#"
        [[params.footer.links.links]]
            title = "Technology Roadmap"
            url = "#"

        [params.footer.contact_form]
            enabled = false
            header = "Get In Touch"
            action = ""
